In [2]:
import numpy as np
import pandas as pd
import os

In [3]:
a = np.array([1,2,22,12,2,3,4,56,7,8,9],dtype="int8")
print(a)

[ 1  2 22 12  2  3  4 56  7  8  9]


In [11]:
for i in range(len(a)):
    print(a[i])

1
2
22
12
2
3
4
56
7
8
9


In [16]:
a.shape

(11,)

In [26]:
b = np.array([[123,23,2,3],232],dtype="object")
print(b.shape)

(2,)


In [33]:
c = np.array([123,"87",222222222222239999999999999999999993333333333134354])

In [3]:
a = np.array([23,32,3,12,3,324,23])

### 

In [5]:
print(list(a))

[23, 32, 3, 12, 3, 324, 23]


In [38]:
mat = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [39]:
mat = np.array(mat)

In [40]:
mat[1,2]

7

In [41]:
mat[1,2]

7

In [42]:
mat[1,]

array([5, 6, 7, 8])

In [43]:
#get specific column
mat[:,2]

array([ 3,  7, 11, 15])

In [44]:
#k[startindex:endindex:steps]

In [48]:
mat[0,::2]

array([1, 3])

In [49]:
 #3darray

In [51]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [56]:
b[1,1,:]

array([7, 8])

In [58]:
m=np.zeros((2,3))

In [59]:
m[0,0]

0.0

In [61]:
np.ones((6,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [63]:
np.ones((6,7,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [66]:
np.full((3,3),67,dtype="int32")

array([[67, 67, 67],
       [67, 67, 67],
       [67, 67, 67]])

In [70]:
np.arange(1,9,3)

array([1, 4, 7])

In [74]:
#(start,stop,nums,endpoint,)
np.linspace(1,3,7,False,False)

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571])

In [75]:
np.linspace(1,5,7)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [76]:
np.full(2,5)

array([5, 5])

In [77]:
np.full((2,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [78]:
np.full_like(mat.shape,7)

array([7, 7])

In [82]:
np.random.rand(4,4)

array([[0.9373267 , 0.48399034, 0.17108043, 0.47388636],
       [0.24385398, 0.38837001, 0.44674082, 0.29633634],
       [0.33114612, 0.27328395, 0.97060493, 0.69820153],
       [0.79816316, 0.80564251, 0.98238271, 0.1728093 ]])

In [87]:
np.random.randint(5,9,size=(3,3))

array([[6, 8, 5],
       [8, 7, 5],
       [5, 6, 6]])

In [88]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
arr = np.array(([1,2,3]))
r1=np.repeat(arr,3,axis=0)

In [95]:
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [96]:
mat = [[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]]

In [97]:
mat

[[1, 1, 1, 1, 1],
 [1, 0, 0, 0, 1],
 [1, 0, 9, 0, 1],
 [1, 0, 0, 0, 1],
 [1, 1, 1, 1, 1]]

In [99]:
#genarate the matrix mat like above using numpy

In [106]:
ones= np.ones((5,5))
zeoros = np.zeros((3,3))
zeoros[1,1] = 9
print(ones)
zeoros

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [109]:
ones[1:-1,1:-1]=zeoros

In [110]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [111]:
n = "0002873"
print(int(n))

2873


In [115]:
nums = ["a","b","c","d"]
print(8%4)

0


In [116]:
n= {}
print(type(n))

<class 'dict'>


In [1]:
import numpy as np

In [8]:
arr = np.random.randint(1,100,size=(5,5))

In [9]:
arr

array([[79, 87, 93, 55, 91],
       [60, 96, 16, 10, 91],
       [22, 25, 23, 44,  1],
       [ 8, 34, 45, 85, 14],
       [37, 58,  2, 51, 71]])

In [13]:
boolarr=(arr%5==0)

In [14]:
newarr = arr[boolarr]

In [1]:
newarr

NameError: name 'newarr' is not defined